### ISSUE TITLE
[REVIEW]: WordTokenizers.jl: Basic tools for tokenizing natural language in Julia

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1956]
**Submitting author:** @oxinabox (<a href="http://orcid.org/0000-0003-1386-1646">Lyndon White</a>)
**Repository:** <a href="https://github.com/JuliaText/WordTokenizers.jl/" target ="_blank">https://github.com/JuliaText/WordTokenizers.jl/</a>
**Version:** v0.5.4
**Editor:** @will-rowe
**Reviewer:** @leios, @ninjin
**Archive:** <a href="https://doi.org/10.5281/zenodo.3663390" target="_blank">10.5281/zenodo.3663390</a>

## Status

[![status](https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81/status.svg)](https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81"><img src="https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81/status.svg)](https://joss.theoj.org/papers/883b18d3c1cfbf8a5b2b53acb1f5ab81)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/JuliaText/WordTokenizers.jl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@leios & @ninjin, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @will-rowe know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaText/WordTokenizers.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oxinabox) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/JuliaText/WordTokenizers.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@oxinabox) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @leios, @ninjin it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1609/aaai.v33i01.33016843 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01956/joss.01956/10.21105.joss.01956.pdf)

**Comment by oxinabox** [comment]
cc @Ayushk4

**Comment by will-rowe** [comment]
Hi @leios and @ninjin. Just chasing up this review - don't worry if you've not started yet, I realise it was the holidays etc.

Please let me know if you need anything. Cheers.

**Comment by will-rowe** [comment]
Hi @leios, @ninjin - just checking in with the reviews here. Can you please let me know when you might expect to have them completed?

**Comment by leios** [comment]
Hey @will-rowe I am really sorry. I had a week to do it, but was finishing my thesis revisions during that time, then I had to move to my new position. I haven't had time to set up my stuff in my new place, so I don't know when I can do a review. By the earliest, this weekend. I am making it a priority to do then, but I understand if you want to try to find a new reviewer. Sorry again for the trouble.

**Comment by ninjin** [comment]
@will-rowe: I should be able to handle it within the week.

**Comment by will-rowe** [comment]
Thanks @leios and @ninjin. Those timelines work for me. Let me know @leios if you don't manage to find time in the next couple of weeks. I'll ping again in a week to chase up

**Comment by leios** [comment]
Hey, trying to start the review. Sorry I'm late. Also sorry if this is a stupid question, but how do I check the boxes? Last time I did a review, I could just click on them, but this time I do not seem to have permission.

**Comment by leios** [comment]
I will submit a PR fixing a number of typos in the README and paper. I have a general question on the scope of this software regarding asian language processing, such as Japanese. I know that this is possible with [TinySegmenter.jl](https://github.com/JuliaStrings/TinySegmenter.jl), but is there a way to use this package with WordTokenizers?

**Comment by Ayushk4** [comment]
WordTokenizer's default tokeniser doesn't work well on some Asian languages like Chinese, Japanese. 

But, we can set up TinySegmenter.jl in the same way as [RevTok.jl example](https://github.com/JuliaText/WordTokenizers.jl#example-setting-tokenizer--revtokjl) given in readme.
Here's an example with the Japanese sample text taken from TinySegmenter.jl.

```
julia> using WordTokenizers

julia> tokenize("आप कैसे हैं?") |> print # Default tokenizer on Hindi
["आप", "कैसे", "हैं", "?"]

julia> tokenize("私の名前は中野です") |> print # Default tokenizer on Japanese 
["私の名前は中野です"]

julia> import TinySegmenter

julia> set_tokenizer(TinySegmenter.tokenize)

julia> tokenize("私の名前は中野です") |> print # TinySegmenter's tokenizer on Japanese
SubString{String}["私", "の", "名前", "は", "中野", "です"]
```

**Comment by leios** [comment]
Ah. I was missing the `.tokenize`. I don't know why I didn't put it there, clearly the documentation does the same thing for Revtok. Thanks!

**Comment by oxinabox** [comment]
> I have a general question on the scope of this software regarding asian language processing, such as Japanese. 

For interest the default tokenizer [TokTok](https://github.com/jonsafari/tok-tok) has:
>  been tested on, and gives reasonably good results for English, Persian, Russian, Czech, French, German, Vietnamese, Tajik, and a few others. 

Which is to say a bunch of languages using the Latin (English, French, German, Vietnamese), or the Cyrillic  (Russian, Czech, Tajik), or Persian alphabet (Farsi).
All of which use space as primary token seperation.

We don't yet have anything that supports the morpheme segementation needed for languages like Japanese or Chinese.

I would speculate, just based on the people involved in JuliaText, we are likely to get support for 1 or more Indian languages before anything else.
Most of which, as I understand it are also space seperated.


> I know that this is possible with TinySegmenter.jl, but is there a way to use this package with WordTokenizers?

@Ayushk4 updated the readme now with that example.
Which i think is a much better one,
as RevTok.jl is unmaintained, and also we have our own built in RevTok these days.

**Comment by leios** [comment]
I don't see the updated readme yet, if you are going to change it, could you use something like, "ジュリアプログラミング言語が大好きです！"

It translate to "I love the Julia programming language!" but also shows how it segments all three alphabets (it lumps Hiragana words together, which might be an issue for some people).

**Comment by will-rowe** [comment]
Hi @leios. You should be able to edit the top comment in this thread - click the 3 dots and then edit to update your checklist (via markdown). Let me know if you're stuck - and thanks for the review!

**Comment by leios** [comment]
@will-rowe I don't have that option, only "copy link" and "quote reply"

**Comment by will-rowe** [comment]
hmmm - did you accept the invite at the top of the thread? Link [here](https://github.com/openjournals/joss-reviews/invitations). If you have already done this, let me know and I'll have to ask someone as I'm out of ideas!

**Comment by leios** [comment]
Sorry, I should have known that was a requirement. Filled in everything now. Thanks!

**Comment by will-rowe** [comment]
Hi @ninjin - just pinging you to see how your review is going? Thanks!

**Comment by ninjin** [comment]
@will-rowe: Ouch, sorry. On it today. Sorry for being the slowest reviewer you have on the roster and thank you for the poke.

@leios: I would prefer: “日本語はひらがなとカタカナと漢字で表されます。” (“Japanese is expressed using hiragana, katakana, and kanji.”) over your example sentence. Sure, this one is way more formal, but yours somehow sounds a bit odd to me. Perhaps because it expresses something somewhat intimate in a formal way?

**Comment by ninjin** [comment]
Repository:

1. No installation instructions as far as I can see. Although a bit silly for Julia, a single reference to the necessary command is enough.

Paper:

1. I do not believe I have ever seen normalisation as a part of tokenisation, thus I would remove: “Such word tokenization also often includes some normalizing, such as correcting unusual spellings or removing all punctuations.”.

2. It may be worth mentioning that “sentence splitting” is another term often used for “sentence segmentation”. For the record, I have never seen “sentence tokenisation” outside of NLTK, but I am happy to be corrected.

Non-mandatory (just comments, really):

1. It may be wise to consider including purely statistical tokenisation algorithms such as those used by BERT and friends. They are becoming more and more popular and I suspect they may be the standard very soon.

2. For some real competition in regards to performance, see [this](https://github.com/huggingface/tokenizers). It went public post-submission though.

All in all, a nice solid package. Well done!

**Comment by will-rowe** [comment]
Thanks for some excellent reviews @leios and @ninjin.

@oxinabox - can you please address @ninjin 's comments and let me know when you are ready for me to take a final look. We should be close to acceptance!

**Comment by oxinabox** [comment]
> Repository:
> 
>     No installation instructions as far as I can see. Although a bit silly for Julia, a single reference to the necessary command is enough.

Done.

> Paper:
> 
>     I do not believe I have ever seen normalisation as a part of tokenisation, thus I would remove: “Such word tokenization also often includes some normalizing, such as correcting unusual spellings or removing all punctuations.”.
> 

I loosely speaking disagre, but:  
I have removed that sentence, as it is overstated. it might be better to say "occucationally" or sometimes. But it doesn't belong right at the start of the paper, but rather in the docstrings of particular tokenizers. Arguably its undersirable behavour.
Examples:
The Twitter Tokenizer (both ours and the original from [NLTK](https://github.com/nltk/nltk/blob/762663e95a1b60affb9d8b9ab40e6a65cec366b8/nltk/tokenize/casual.py#L270-L272
)) normalizes: `waaaaayyyy` into `waaayyy`.

Apparently the [Stanford Tokenizer has a `americanize` flag](https://github.com/nltk/nltk/blob/762663e95a1b60affb9d8b9ab40e6a65cec366b8/nltk/tokenize/stanford.py#L33-L35)
which normalizes: `colour` to `color`.
(Though this really feels like it is stepping out side the bounds of normalizing during tokenization).

On the more minor end, the [original Penn tokenizer](https://github.com/JuliaText/WordTokenizers.jl/blob/master/src/words/penn.sed#L53)  normalizes `"` (double quote) to `''` (pair of single quote).

>    It may be worth mentioning that “sentence splitting” is another term often used for “sentence segmentation”. For the record, I have never seen “sentence tokenisation” outside of NLTK, but I am happy to be corrected.

Done in https://github.com/JuliaText/WordTokenizers.jl/pull/45
my coauthor will post here one merged

> Non-mandatory (just comments, really):
> 
>     It may be wise to consider including purely statistical tokenisation algorithms such as those used by BERT and friends. They are becoming more and more popular and I suspect they may be the standard very soon.
> 

Good idea, https://github.com/JuliaText/WordTokenizers.jl/issues/44


>     For some real competition in regards to performance, see this. It went public post-submission though.

I think that will indeed be significantly hard to been, but we should see  how we measure up.
https://github.com/JuliaText/WordTokenizers.jl/issues/46
Beyond scope of this submission though.



> All in all, a nice solid package. Well done!

Thanks

**Comment by ninjin** [comment]
@oxinabox: Agreed, if it was “occasionally” I would agree. I think there are alternative explanations for your examples though. The first two are examples of canonicalisation that most likely have been integrated into the tokeniser because it is the first piece of code that touches the “raw” text. For PTB, these are necessary for the text to be consistent with the pre-processing that PTB did back in the 90s.

Thanks again for a solid package and I am 200% in support of https://github.com/JuliaText/WordTokenizers.jl/issues/44!

**Comment by Ayushk4** [comment]
The changes have been made to the paper. Thanks, @ninjin  for the suggestions.

**Comment by Ayushk4** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01956/joss.01956/10.21105.joss.01956.pdf)

**Comment by will-rowe** [comment]
Great! Thank you everyone. I'll give it a final read through now

**Comment by will-rowe** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1609/aaai.v33i01.33016843 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by will-rowe** [comment]
Okay - everything looks good to me. Please can you tag a final release and archive it - post the version number and DOI back here.

**Comment by oxinabox** [comment]
DOI: 10.5281/zenodo.3648713
Version 0.5.4

Thanks

**Comment by will-rowe** [comment]
Thanks @oxinabox . The author names on the archive should match the paper authors please

**Comment by oxinabox** [comment]
> Thanks @oxinabox . The author names on the archive should match the paper authors please

I am not sure what is controlling the names in the archive.
All the people who as not listed on the paper, who are listed in the archive have made only small corrections to the spelling in the Readme or comments. (Bar one who made a [small fix](https://github.com/JuliaText/WordTokenizers.jl/commit/e3f8d936053f612bd9bf2326b9f35e53fc15c354) to a correr case in the regex.)
These changes are appreciated, but I assume fall below the contribution threashold for co-author ship on a JOSS paper.
Perhaps I am wrong though?

**Comment by will-rowe** [comment]
No - you can have the author list as you'd like it (i.e. your in paper). I'm not sure why zenodo has autofilled in all of those authors. You can click edit on the zenodo page and then manually remove the authors which are not on your paper.

**Comment by danielskatz** [comment]
You can use a zenodo.json file to tell zenodo what you want automatically, but it's not as easy as it should be be - see https://github.com/zenodo/zenodo/issues/1606 for some discussion on this

**Comment by oxinabox** [comment]
Ok, should be fixed

**Comment by will-rowe** [comment]
@whedon set 10.5281/zenodo.3648713 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3648713" target="_blank">10.5281/zenodo.3648713</a> is the archive.

**Comment by will-rowe** [comment]
@whedon set v0.5.4 as version

**Comment by whedon** [comment]
OK. v0.5.4 is the version.

**Comment by will-rowe** [comment]
Thanks @oxinabox for a nice submission. And many thanks to @leios and @ninjin for your excellent reviews.

Pinging @openjournals/joss-eics to move this to acceptance

**Comment by kthyng** [comment]
@oxinabox I'm taking over for the rest of your submission. Can you edit the Zenodo data a little more, so that the title matches that of your paper?

**Comment by kthyng** [comment]
@oxinabox I've made some changes to your text and bib file in PRs. Please merge what you agree with: [#47](https://github.com/JuliaText/WordTokenizers.jl/pull/47) and [#48](https://github.com/JuliaText/WordTokenizers.jl/pull/48)

**Comment by oxinabox** [comment]
done, thanks good changes

**Comment by kthyng** [comment]
> @oxinabox I'm taking over for the rest of your submission. Can you edit the Zenodo data a little more, so that the title matches that of your paper?

@oxinabox Ok also this part.

**Comment by oxinabox** [comment]
> > @oxinabox I'm taking over for the rest of your submission. Can you edit the Zenodo data a little more, so that the title matches that of your paper?
> 
> @oxinabox Ok also this part.

I thought I did so.
I don't know why Zenodo is not showing the new title.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/5127634/74091799-a8370180-4ab3-11ea-96f0-9247c86546c7.png">

**Comment by kthyng** [comment]
@oxinabox Is the metadata updated when you look at it online? It still isn't for me. Maybe this will help? https://github.com/geodynamics/best_practices/blob/master/ZenodoBestPractices.md

**Comment by oxinabox** [comment]
Ok, not sure what is going on with Zenodo, but i cut a new release on github and that one editted fine.

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3663390.svg)](https://doi.org/10.5281/zenodo.3663390)|

10.5281/zenodo.3663390

**Comment by kthyng** [comment]
Ok great!

**Comment by kthyng** [comment]
@whedon set 10.5281/zenodo.3663390 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3663390" target="_blank">10.5281/zenodo.3663390</a> is the archive.

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1609/aaai.v33i01.33016843 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1322

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1322, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1230174245914914816) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1323
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01956](https://doi.org/10.21105/joss.01956)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by kthyng** [comment]
@openjournals/dev There is something wrong with the paper DOI. This seems to keep happening to me. How can I prevent it/watch for it in the future?

**Comment by kyleniemeyer** [comment]
@kthyng the DOI resolves for me, so it may just be a caching issue with your browser? Though sometimes it does take a few minutes or longer for it to initially resolve, which is a Crossref issue, I think.

**Comment by arfon** [comment]
> @openjournals/dev There is something wrong with the paper DOI. This seems to keep happening to me. How can I prevent it/watch for it in the future?

It takes a few mins for the DOI to register, plus sometimes, the DOI resolves before the GitHub Pages build is ready (so the PDF doesn't render).

Basically I recommend waiting a few mins before clicking the DOI link, and when rechecking, it sometimes helps to (re)try in incognito/private mode too to help your browser avoid caching issues.

**Comment by danielskatz** [comment]
Sometimes I retry from a different network (e.g., phone vs wifi), since the caching seems to happen in the specific network somewhere.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01956/status.svg)](https://doi.org/10.21105/joss.01956)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01956">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01956/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01956/status.svg
   :target: https://doi.org/10.21105/joss.01956
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01956/status.svg)](https://doi.org/10.21105/joss.01956)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by kthyng** [comment]
@arfon @kyleniemeyer Sorry about the unwarranted alert! When I checked, it was showing up as the orange-ish not-working page, which in the past had meant a different problem, rather than the blue-ish the-DOI-just-hasn't-resolved-yet page.

**Comment by kthyng** [comment]
A belated congratulations to @oxinabox on your new paper! Thanks to @will-rowe for editing and to reviewers @leios and @ninjin — we really appreciate your time and expertise!
