### ISSUE TITLE
[REVIEW]: ocean_data_tools: A MATLAB toolbox for interacting with bulk freely-available oceanographic data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2497]
**Submitting author:** @lnferris (<a href="http://orcid.org/0000-0001-6446-9340">L. N. Ferris</a>)
**Repository:** <a href="https://github.com/lnferris/ocean_data_tools" target ="_blank">https://github.com/lnferris/ocean_data_tools</a>
**Version:** v1.0.1
**Editor:** @kthyng
**Reviewers:** @kakearney, @castelao
**Archive:** <a href="https://doi.org/10.5281/zenodo.4151538" target="_blank">10.5281/zenodo.4151538</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd/status.svg)](https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd"><img src="https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd/status.svg)](https://joss.theoj.org/papers/83f5dd842625232afa133d9636cffcfd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lnferris/ocean_data_tools" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@castelao & @kakearney, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kthyng know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lnferris/ocean_data_tools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lnferris) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lnferris/ocean_data_tools">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lnferris) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @castelao, @chadagreene it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.11646/zootaxa.4802.1.5 is OK
- 10.1111/ddi.13079 is OK
- 10.5281/zenodo.3928714 is OK
- 10.1126/science.277.5334.1956 is OK
- 10.5670/oceanog.2016.66 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.02497/joss.02497/10.21105.joss.02497.pdf)

**Comment by kthyng** [comment]
@castelao, @chadagreene, here is where the review happens.

**Comment by kthyng** [comment]
@whedon remind @reviewer in 2 weeks

**Comment by whedon** [comment]
@reviewer doesn't seem to be a reviewer or author for this submission.

**Comment by kthyng** [comment]
heh, oops.

**Comment by kthyng** [comment]
@whedon remind @chadagreene in 2 weeks

**Comment by whedon** [comment]
Reminder set for @chadagreene in 2 weeks

**Comment by chadagreene** [comment]
Hmm, I officially accepted the invitation to review a couple hours ago, and now my email is getting flooded by emails with the subject line starting 

Re: [openjournals/joss-reviews] [PRE REVIEW]: 

and they are all unrelated to the review I accepted the invitation for. I have hit "unsubscribe" on about 10 of these emails so far, yet they keep rolling in. Anybody know how I can stop receiving these emails?

**Comment by danielskatz** [comment]
see the comments further up in this issue - there are screenshots that show how to do this

**Comment by chadagreene** [comment]
Got it, thanks @danielskatz!

**Comment by lnferris** [comment]
@chadagreene I am implementing documentation using relative links between markdown files. E.g. https://github.com/lnferris/ocean_data_tools#building-uniform-structs-from-data-sources-1 links to https://github.com/lnferris/ocean_data_tools/blob/master/docs/argo_build.md

**Comment by kthyng** [comment]
@chadagreene please see the issues I started on your behalf above, and create similar issues for future comments. Then usually there is a short summary of a review actually in this review issue that refers to the open issues. There is a bit of bookkeeping with this setup.

@lnferris Can you copy and paste your comments that have been in response to these comments from @chadagreene into the relevant issue above? This way, it is clear what work has been done on a given issue, as well as it being clear when it is finished since the issue can be closed.

**Comment by whedon** [comment]
:wave: @chadagreene, please update us on how your review is going.

**Comment by lnferris** [comment]
@kthyng Just to confirm I don't need to be doing anything on my end, correct?

**Comment by kthyng** [comment]
@lnferris Looks like you've addressed the comments that have come in, so just wait for more input from the reviewers once they get going.

Friendly ping to @chadagreene and @castelao about this review.

**Comment by kthyng** [comment]
Hi @lnferris I have heard from @chadagreene that he won't be able to review your submission, unfortunately. I will remove him as a reviewer and search for another reviewer.

In the meantime, a ping to @castelao to keep this on his radar!

**Comment by kthyng** [comment]
Hi @kakearney! @chadagreene suggested that you would be a good reviewer for this package. Are you interested in reviewing this for JOSS? The review process is of the software itself and a short paper, and since this is already the review issue on github, you can see the checklist-based approach above. You can also get more information here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html
I would hope for the review in the next 3-4 weeks if possible since this review time period has already started, but I can be flexible if needed.

**Comment by lnferris** [comment]
@kthyng it looks like @castelao isn't an assignee, are they supposed to be assigned?

**Comment by kthyng** [comment]
@lnferris He might not have accepted the invitation to review yet. I'll invite again just in case.

**Comment by kthyng** [comment]
@whedon re-invite @castelao as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@castelao please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kakearney** [comment]
Yes, I can review this, and should be able to meet the 3-4 week deadline.

-Kelly

**Comment by kthyng** [comment]
@kakearney awesome! I am going to do a reviewer switcharoo on this issue above. I will invite you as a reviewer after a few steps and let me know if you don't have permission to edit the checklist after you accept the invitation (which should be emailed to you).

**Comment by kthyng** [comment]
@whedon remove @chadagreene as reviewer

**Comment by whedon** [comment]
OK, @chadagreene is no longer a reviewer

**Comment by kthyng** [comment]
@whedon add @kakearney as reviewer

**Comment by whedon** [comment]
OK, @kakearney is now a reviewer

**Comment by kthyng** [comment]
@whedon add @castelao as reviewer

**Comment by whedon** [comment]
OK, @castelao is now a reviewer

**Comment by kthyng** [comment]
@whedon invite @kakearney as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by kthyng** [comment]
@whedon re-invite @kakearney as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@kakearney please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kthyng** [comment]
@whedon remove @castelao as reviewer

**Comment by whedon** [comment]
OK, @castelao is no longer a reviewer

**Comment by kthyng** [comment]
@whedon add @castelao as reviewer

**Comment by whedon** [comment]
OK, @castelao is now a reviewer

**Comment by kthyng** [comment]
things should be good to go, let me know if otherwise.

**Comment by castelao** [comment]
Hi @kthyng , how do I update my review checklist? Was I supposed to have editing permissions on the very first post?

**Comment by kthyng** [comment]
@whedon re-invite @castelao as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@castelao please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by kthyng** [comment]
@castelao you can click on the link above. 👆

**Comment by castelao** [comment]
@kthyng , it's working. Thanks!

**Comment by kthyng** [comment]
Hi @castelao and @kakearney! Do you have a timeline in mind for when you could work on your reviews? Thanks!

**Comment by kakearney** [comment]
I’ll be submitting mine this afternoon... just compiling all my notes into
issues and a summary now.

**Comment by kakearney** [comment]
In my review checklist, I have checked off the places where I think this submission meets the requirements of JOSS.  Overall, I believe this is a nice toolbox that fills a need in the ocean data community.  However, I do have a few concerns about the current functionality of the toolbox.  I believe the issues I have raised should be able to be corrected without too much additional effort.

To test the toolbox, I worked through the demo examples, adding a few variations of my own to each function call.  The following issues are ones that I believe need to be addressed before this toolbox is published in JOSS:

- Input parsing and validation (lnferris/ocean_data_tools#10)
- Bathymetry data reloaded for plots (lnferris/ocean_data_tools#11)
- Remove eval (lnferris/ocean_data_tools#12)
- Revise or remove more\_colors (lnferris/ocean_data_tools#13)
- Plotting function customization (lnferris/ocean_data_tools#14)
- Longitude wrapping (lnferris/ocean_data_tools#15)
- Revise or remove netcdf\_info (lnferris/ocean_data_tools#16)
- argo\_build confuses pressure and depth (lnferris/ocean_data_tools#17)
- Rename bathymetry\_region (lnferris/ocean_data_tools#18)
- Bathymetry plotting along a transect (lnferris/ocean_data_tools#19)

I also sumbitted a number of enhancement requests as issues.  These are not things that I believe need to be addressed before publication, but would be nice if they could be addressed eventually:

- general\_depth\_subset z-axis (lnferris/ocean_data_tools#20)
- Selection popup instructions (lnferris/ocean_data_tools#21)
- Remove external dependency on nctoolbox (lnferris/ocean_data_tools#22)
- Unsuppressed command window output (lnferris/ocean_data_tools#23)
- Plot versus distance along transect (lnferris/ocean_data_tools#24)
- transect\_select point density (lnferris/ocean_data_tools#25)

Regarding documentation, this submission includes a fair amount of it.  However, given that the target audience is likely to consist at least in part of novice programmers, I believe it could be more comprehensive.  In particular, the in-file header documentation needs to explicitly describe the input requirements for each function.  My comments on documentation have been submitted as issues:

- Installation instructions (lnferris/ocean_data_tools#26)
- GSW compatibility (lnferris/ocean_data_tools#27)
- Markdown documentation vs Matlab docs (lnferris/ocean_data_tools#28)
- In-file documentation (lnferris/ocean_data_tools#29)
- Automated tests (lnferris/ocean_data_tools#30)
- Demo script hard-coded paths (lnferris/ocean_data_tools#31)

The overview paper provides a very brief summary of the toolbox's primary purpose. Given the target audience, I suggest providing a bit more context.  For example, the first paragraph introduces the "structs" that are the common currency of this toolbox.  I suggest defining this term, describing the format in more detail (e.g. what types of data are possible fields in these structures?), and explaining why this method of organizing data may be more user-friendly than the native data storage of underlying datasets.  Note that while "struct" is common shorthand for "structure array" among Matlab users, the Matlab documentation favors using the full name whenever discussing variables of this class, and I recommend this paper do likewise.  Also, the paper does not mention why Matlab was chosen as the language of choice for this toolbox.  I recommend highlighting that Matlab is already extensively used within the oceanographic community.

The final paragraph mentions that the toolbox "has already been used in scientific publications."  I scanned the Crear et al., 2020 paper (Bemis et al., 2020 requires registration to view, and I opted out), and it doesn't appear that the toolbox data structures or plots are used directly in the paper.  I recommend changing the phrasing here to indicate that the toolbox was used for data exploration in support of these publications, rather than as the focal point of the studies.

Finally, as a generic ocean data exploration tool, I recognize that's its a bit difficult to state how this toolbox fits into the state of the field.  There are a number of semi-related ocean/climate Matlab toolboxes out there: for example, Chad Greene's Climate Data Toolbox, Rich Pawlowicz's various tools (tides, air-sea fluxes, mapping, etc.), Rich Signell's SEA-MAT tools, the Oceans Toolbox, the GSW Toolbox (and its deprecated but still commonly-used precessor, the seawater toolbox).  I'm not aware of any other publically-available, documentated, and designed-to-be-shared toolbox filling the same data exploration niche as this one.  Perhaps speak to this point somewhere in the paper?

To the authors, I hope the sudden flood of issues does not appear too negative!  I think this toolbox will serve the needs of a wide variety of users intimidated by the ever-growing variety of field- and model-derived oceanographic datasets. I look forward to seeing how this toolbox evolves in the future.

-Kelly Kearney

**Comment by lnferris** [comment]
Thank you for your extremely detailed review, @kakearney!! I will get started on these edits as soon as I can. @kthyng, what is my timeline for making corrections?

**Comment by kthyng** [comment]
@lnferris There isn't a specific deadline, but I would say if you plan to take a hiatus from this review issue for more than a few weeks, we can pause the issue in the meantime while you work in the background. If you want to work and reply here along the way for the various issues, then we don't need to pause and you can just work along. Does that make sense?

**Comment by castelao** [comment]
@lnferris and @kthyng , I'm sorry for my slow response. I'll point my comments as issues in the project repository, and I'll make it clear what I consider critical from suggestions.

Impressive the review from @kakearney. Nice job!

**Comment by lnferris** [comment]
@castelao and @kakearney thank you both for your comments! @kthyng I can start working on these issues now.

**Comment by lnferris** [comment]
I have fixed and closed "Revise or remove more_colors (lnferris/ocean_data_tools#13)".

**Comment by lnferris** [comment]
I have fixed and closed "Revise or remove netcdf_info (lnferris/ocean_data_tools#16)".

**Comment by lnferris** [comment]
I have fixed and closed "Rename bathymetry_region (lnferris/ocean_data_tools#18)".

**Comment by lnferris** [comment]
I have fixed and closed "argo_build confuses pressure and depth (lnferris/ocean_data_tools#17)".

**Comment by lnferris** [comment]
I have fixed and closed "Remove eval (lnferris/ocean_data_tools#12)".

**Comment by lnferris** [comment]
I have fixed and closed "Demo script hard-coded paths (lnferris/ocean_data_tools#31)".

**Comment by lnferris** [comment]
I have fixed and closed "Bathymetry data reloaded for plots (lnferris/ocean_data_tools#11)".

**Comment by lnferris** [comment]
I have fixed and closed "Selection popup instructions (lnferris/ocean_data_tools#21)".

**Comment by lnferris** [comment]
I have fixed and closed "Bathymetry plotting along a transect (lnferris/ocean_data_tools#19)".

**Comment by lnferris** [comment]
I have fixed and closed "DOI for each release  (lnferris/ocean_data_tools#33)".

**Comment by lnferris** [comment]
I have fixed and closed "general_depth_subset z-axis (lnferris/ocean_data_tools#20)".

**Comment by lnferris** [comment]
I have fixed and closed "Unsuppressed command window output (lnferris/ocean_data_tools#23)".

**Comment by lnferris** [comment]
I have fixed and closed "Plotting function customization (lnferris/ocean_data_tools#14)".

**Comment by lnferris** [comment]
I have fixed and closed "GSW compatibility (lnferris/ocean_data_tools#27)".

**Comment by lnferris** [comment]
I have fixed and closed "Installation instructions (lnferris/ocean_data_tools#26)".

**Comment by lnferris** [comment]
I have fixed and closed "In-file documentation (lnferris/ocean_data_tools#29)".

**Comment by lnferris** [comment]
I have fixed and closed "Input parsing and validation (lnferris/ocean_data_tools#10)".

**Comment by lnferris** [comment]
Hello @kthyng @kakearney @castelao! I believe I have addressed the required issues and some of the suggested issues (hope to get to the others when time allows). The only one marked as required which I have chosen not to implement is #28; there is an explanation about this in the issue itself. Please let me know if there are more changes and or/tasks needed from my end. Thanks again for your detailed reviews.

**Comment by lnferris** [comment]
I have fixed and closed "Plot versus distance along transect (lnferris/ocean_data_tools#24)".

**Comment by lnferris** [comment]
@kthyng at this point I wait for reviewers, correct?

**Comment by lnferris** [comment]
I have fixed and closed "transect_select point density (lnferris/ocean_data_tools#25)".

**Comment by kthyng** [comment]
Ok I see issues #28 and #34 which I have commented on there. I would like to hear from the reviewers there if possible @castelao @kakearney.

@kakearney is #30 meant to be a suggestion? 

Generally I'd like to hear from both reviewers about their responses to the author responses. Thank you.

**Comment by lnferris** [comment]
@kthyng, thanks for the update; sounds good! Also, I added a new function (glider_build, for US IOOS archived glider data) since they reviewed. I documented it the same way as the others, but let me know if anyone has an issue with this.

**Comment by kakearney** [comment]
Regarding the highlighted issues, lnferris/ocean_data_tools#28 was only a suggestion on my part.    lnferris/ocean_data_tools#30 was more of a requirement; it looks like the recent updates do add much better input parsing and validation, but I have not yet had a chance to run any tests of my own (and likely won't for another two weeks due to workload).

More details regarding 28:

Within the Matlab desktop application, function help can be provided in two forms, typically called help and doc files.  The "help" function displays plain-text info, and pulls that info from the header of each function/script file; I consider this (with description, syntax, input/output parameter descriptions, etc.) to be mandatory for shared code, and a brief perusal suggests that the updates associated with lnferris/ocean_data_tools#29 now fulfill this requirement.  

More in-depth documentation can be accessed via Matlab's "doc" function, which loads html-formatted files that typically repeat the in-file documentation and also provide further context, examples, etc; all of Matlab's native functions include these but they aren't very common in third-party toolboxes.  So I wouldn't say it's a requirement to add it to this toolbox.  However, Ferris has already done the work creating markdown documentation for all of the functions, and I would encourage them to reconsider converting it to html as time permits in the future.  End users are far more likely to browse documentation from within the Matlab help viewer (i.e. doc) than they are to revisit the GitHub repo.

**Comment by lnferris** [comment]
@kakearney Do you recommend a particular markdown-to-html converter?

**Comment by kakearney** [comment]
Most of my own documentation is written in Matlab and converted directly to
html via Matlab's publish function.  I also use my own publishreadme
<https://github.com/kakearney/publishreadme-pkg> Matlab function to
publish marked-up
Matlab scripts
<https://www.mathworks.com/help/matlab/matlab_prog/marking-up-matlab-comments-for-publishing.html>
directly
to both html and Github-flavored markdown.  I don't have specific
recommendations for going from markdown to html.

**Comment by lnferris** [comment]
@kakearney I implemented the Matlab documentation and mentioned the availability of this documentation under "Accessing Help" in the GitHub readme. For future reference, I used [grip](https://github.com/joeyespo/grip) to convert markdown to html.

<img width="1043" alt="Screen Shot 2020-09-25 at 2 42 30 AM" src="https://user-images.githubusercontent.com/24570061/94235028-dea57d80-fed8-11ea-9c12-494d9fc3a8ed.png">

**Comment by lnferris** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: :point_left:

**Comment by lnferris** [comment]
I have fixed and closed "Community guidelines (lnferris/ocean_data_tools#37)".

**Comment by lnferris** [comment]
I have fixed and closed "DOIs of the datasets (lnferris/ocean_data_tools#36)".

**Comment by lnferris** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
At present, we need to hear from both reviewers @kakearney and @castelao regarding the reviewer checklists above which have not been completed to see what issues remain. We have already heard from @kakearney about a plan to check some tests, but that it will take a little bit to get back to this.

**Comment by lnferris** [comment]
Sounds good @kthyng. @kakearney @castelao please let me know if you need anything from my end.

**Comment by kthyng** [comment]
> Regarding the highlighted issues, [lnferris/ocean_data_tools#28](https://github.com/lnferris/ocean_data_tools/issues/28) was only a suggestion on my part. [lnferris/ocean_data_tools#30](https://github.com/lnferris/ocean_data_tools/issues/30) was more of a requirement; it looks like the recent updates do add much better input parsing and validation, but I have not yet had a chance to run any tests of my own (and likely won't for another two weeks due to workload).

@kakearney Will you be able to return to this and run tests on the recent updates?

**Comment by kthyng** [comment]
@castelao Can you please let us know the status of your review, noting that some of the check boxes above are unchecked? Thanks

**Comment by kakearney** [comment]
I believe I should have time in a few days; I will aim to have my re-review
completed by Oct. 26.

**Comment by kakearney** [comment]
After perusing the updates, I have gone ahead and checked off the remaining items on my reviewer checklist.  Given the size of the toolbox and my current schedule, I wasn't able to run comprehensive tests on all the functions.  However, I did repeat my earlier running of the demos.m script, along with a few modifications to test input flexibility, and only encountered a few minor issues (see below).  I was very glad to see the updated input checks and improved documentation that addressed the bulk of my earlier comments.   

I believe that the toolbox is now at a sufficient level for publication.  Thanks!

Demos.m comments:

- Line 244 of the demo still contains a hard-coded path; this should be added to the relative paths at the beginning of the demos.m script.
- Many path names in the demos.m script, and possibly elsewhere, assume *nix/Mac path conventions (i.e. forward slash as a path separator).  This may cause things to crash on Windows systems.  Path names should be constructed using `fullfile`, `pathsep`, etc. to keep them platform-independent.
- The input parsing and checking is much improved!  But there are still a few places where things fall through the cracks, notably with file input.  It would be nice if the various functions verified that files exist before they try to open them.  At the very least, some checks should be added to the demos.m file to make sure the user-modified bathymetry_dir path points to a valid file, and to error out gracefully if it does not.  For example, if a user were to ignore the instructions to modify the path (and I guarantee you most of them will!), this is the error they will get:

```
Error using netcdf.open (line 52)
Could not open file
'/Users/lnferris/Documents/data/bathymetry/topo_20.1.nc'.

Error in bathymetry_extract (line 51)
nc = netcdf.open(bathymetry_dir, 'NOWRITE'); % open the
file as netcdf datasource.

Error in demos (line 58)
bathymetry_plot(bathymetry_extract(bathymetry_dir,bounding_region(argo)),'2Dcontour') 
```

**Comment by kthyng** [comment]
@castelao We need to hear back from you in this review! What is your review status?

**Comment by lnferris** [comment]
If he does not come back, do we start over again?

**Comment by kthyng** [comment]
@lnferris haha, no don't worry. I reached out by email too and verified he'll be back soon.

**Comment by castelao** [comment]
@kthyng , after going through the review checklist, I believe that this submission satisfies all the requirements for JOSS and is ready for publication.

Congratulations on the great work, @lnferris  .

**Comment by lnferris** [comment]
Thank you @castelao, and thank you very much for reviewing!

**Comment by lnferris** [comment]
I created a new release (1.0.1) and switched the cited DOI to this release.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02497/joss.02497/10.21105.joss.02497.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@lnferris Ok I found the Zenodo doi you made (10.5281/zenodo.4151538). This will be linked into your publication formally through the paper separately from your citation of it, too. Can you go to the Zenodo archive and update the title and author list to exactly match your JOSS paper?

**Comment by kthyng** [comment]
@whedon set v1.0.1 as version

**Comment by whedon** [comment]
OK. v1.0.1 is the version.

**Comment by kthyng** [comment]
@lnferris I have a small change here you can merge if you agree [#40](https://github.com/lnferris/ocean_data_tools/pull/40)

**Comment by lnferris** [comment]
@kthyng Changed Zenodo title and author list, and merged the change. Thanks!

**Comment by kthyng** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.11646/zootaxa.4802.1.5 is OK
- 10.1111/ddi.13079 is OK
- 10.5281/zenodo.4151538 is OK
- 10.1126/science.277.5334.1956 is OK
- 10.5670/oceanog.2016.66 is OK
- 10.1029/2019GC008392 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1884

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1884, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kthyng** [comment]
@openjournals/dev the XML title doesn't have underscores that should be present. How should we proceed? Thanks.

**Comment by arfon** [comment]
> @openjournals/dev the XML title doesn't have underscores that should be present. How should we proceed? Thanks.

Let's proceed with the submission and I'll fix this after we've published.

**Comment by kthyng** [comment]
ok thanks @arfon

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1322264390448676864) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1886
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02497](https://doi.org/10.21105/joss.02497)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your publication @lnferris!! Many thanks to reviewers @kakearney and @castelao for sharing your time and expertise. We couldn't do this process without you!!

once the DOI resolves, I'll close this issue. And @arfon will be able to fix the XML file at this point.

**Comment by kthyng** [comment]
Ok DOI resolves but I guess the issue should stay open until we hear from @arfon.

**Comment by arfon** [comment]
> Ok DOI resolves but I guess the issue should stay open until we hear from @arfon.

Should all be fixed up now.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02497/status.svg)](https://doi.org/10.21105/joss.02497)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02497">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02497/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02497/status.svg
   :target: https://doi.org/10.21105/joss.02497
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02497/status.svg)](https://doi.org/10.21105/joss.02497)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by lnferris** [comment]
Thank you, @kthyng @kakearney @castelao @chadagreene for sharing your time and wisdom. This has been an awesome experience.
