### ISSUE TITLE
[PRE REVIEW]: BESOS: Building and Energy Systems Optimization and Surrogate-modelling

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2620]
**Submitting author:** @TheoChristiaanse (<a href="http://orcid.org/0000-0003-4082-3338">Theodor Victor Christiaanse</a>)
**Repository:** <a href="https://gitlab.com/energyincities/besos/" target ="_blank">https://gitlab.com/energyincities/besos/</a>
**Version:** 1.6.1
**Editor:** @sjpfenninger
**Reviewers:** @fneum, @willu47
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @TheoChristiaanse. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @sjpfenninger.

@TheoChristiaanse if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.75 s (200.1 files/s, 91665.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          49           1633           1847           6538
Jupyter Notebook                68              0          53426           3314
Markdown                         3             73              0            264
reStructuredText                19            310            703            160
TeX                              1              6              0            159
YAML                             6             27             22            144
DOS Batch                        1              8              1             27
INI                              1              3              5             14
make                             1              4              6             10
Bourne Shell                     1              3              6              7
-------------------------------------------------------------------------------
SUM:                           150           2067          56016          10637
-------------------------------------------------------------------------------


Statistical information for the repository '2620' was gathered on 2020/08/31.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
@pengxu1993                      9           435            134            0.52
Boris Kudryavtsev                1             1              1            0.00
C Kwan                           4           135             10            0.13
Cameron Kwan                    20          1036            434            1.34
Chase                           35           657            582            1.13
Dylan                            1             8              8            0.01
Evan Guo                        44           611            341            0.87
Goh Sato                        33          3186           1660            4.43
Juan Comish                      2           120             16            0.12
Mark Hills                      44         14197          11805           23.76
Paul Kovacs                     26         19069           5054           22.04
Ross Alexandra                  30          2167            652            2.58
Theo Christiaanse                6          1540           1732            2.99
Unknown                         26           752            442            1.09
Will                           122          9824           8669           16.90
Will Beckett                   132          3656          16046           18.00
Ximing (Evan) Guo                7           614            989            1.46
theochri                        10            65             32            0.09
theochristiaanse                 2          1350           1026            2.17
unknown                          7            41             27            0.06
westerm                          8           322             11            0.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
C Kwan                      498          368.9          5.2                9.24
Chase                       452           68.8          6.1               19.91
Dylan                         7           87.5          4.3                0.00
Evan Guo                    487           79.7          9.0                6.98
Goh Sato                   2205           69.2          9.2                0.59
Mark Hills                 1530           10.8         18.8               13.73
Paul Kovacs                 144            0.8         20.2               61.81
Theo Christiaanse           174           11.3          3.9               39.08
Unknown                     233           31.0         14.5               24.46
Will Beckett               3156           86.3          5.3               13.62
theochristiaanse           1161           86.0         12.2               18.17
unknown                      20           48.8          3.7               25.00
westerm                     273           84.8         13.8               15.75
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2620 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/2620/paper.md): mapping values are not allowed in this context at line 19 column 44 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon.rb:85:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-132474d2711b/bin/whedon:119:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kthyng** [comment]
Hi @sjpfenninger are you interested in editing this submission?

**Comment by kthyng** [comment]
@whedon invite @sjpfenninger as editor

**Comment by whedon** [comment]
@sjpfenninger has been invited to edit this submission.

**Comment by TheoChristiaanse** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02620/joss.02620/10.21105.joss.02620.pdf)

**Comment by sjpfenninger** [comment]
@whedon assign @sjpfenninger as editor

**Comment by whedon** [comment]
OK, the editor is @sjpfenninger

**Comment by sjpfenninger** [comment]
@kthyng  Yes, happy to edit this (apologies for the delayed response)

**Comment by sjpfenninger** [comment]
@TheoChristiaanse Thanks for your submission! A very quick initial comment is that was not straightforward for me to:

1. find the documentation (the links to the notebooks and tutorials at https://besos.uvic.ca/#documentation don't work )
2. understand which parts of this can be run offline and how that relates to what you describe as the "cloud-based portal" -- is what you offer online simply a hosted version of what is installable as a Python package?
3. understand how BESOS relates to PyEHub which is linked to first thing on https://besos.readthedocs.io/en/stable/

**Comment by sjpfenninger** [comment]
@fneum would you be willing to review this submission for JOSS?

**Comment by fneum** [comment]
@sjpfenninger yes, happy to review this submission.

**Comment by sjpfenninger** [comment]
@whedon add @fneum as reviewer

**Comment by whedon** [comment]
OK, @fneum is now a reviewer

**Comment by sjpfenninger** [comment]
@fneum Great, thanks! As soon as I have a second reviewer, we'll start the review proper.

**Comment by TheoChristiaanse** [comment]
> 
> 
> @TheoChristiaanse Thanks for your submission! A very quick initial comment is that was not straightforward for me to:
> 
>     1. find the documentation (the links to the notebooks and tutorials at https://besos.uvic.ca/#documentation don't work )
> 
>     2. understand which parts of this can be run offline and how that relates to what you describe as the "cloud-based portal" -- is what you offer online simply a hosted version of what is installable as a Python package?
> 
>     3. understand how BESOS relates to PyEHub which is linked to first thing on https://besos.readthedocs.io/en/stable/

Thanks for the notification. I've noticed that the docs haven't been merged yet. Will fix ASAP.

**Comment by TheoChristiaanse** [comment]
should be fixed now!

**Comment by sjpfenninger** [comment]
@whedon add @willu47 as reviewer

**Comment by whedon** [comment]
OK, @willu47 is now a reviewer

**Comment by sjpfenninger** [comment]
@TheoChristiaanse Thanks -- the links at https://besos.uvic.ca/#documentation still don't work for me. I'll leave it up to the reviewers to examine the updated docs more closely, but at first glance it's now clearer how the package relates to the platform.

**Comment by sjpfenninger** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/2677.

**Comment by sjpfenninger** [comment]
@fneum , @willu47 thanks for agreeing to review. Let's head over to #2677  for the actual review!
