### ISSUE TITLE
[PRE REVIEW]: ExoTETHyS II: SAIL on a TRIP with BOATS

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2745]
**Submitting author:** @gmorello (<a href="http://orcid.org/0000-0002-4262-5661">Giuseppe Morello</a>)
**Repository:** <a href="https://github.com/ucl-exoplanets/ExoTETHyS" target ="_blank">https://github.com/ucl-exoplanets/ExoTETHyS</a>
**Version:** v2.0.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**Author instructions**

Thanks for submitting your paper to JOSS @gmorello. **Currently, there isn't an JOSS editor assigned** to your paper.

@gmorello if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.17 s (120.4 files/s, 25372.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           7            452            670           2226
XML                              6              0              0            384
Markdown                         5            124              0            346
TeX                              2             11              0            197
YAML                             1              0              4             13
-------------------------------------------------------------------------------
SUM:                            21            587            674           3166
-------------------------------------------------------------------------------


Statistical information for the repository 'b3cc98f188935ffb5c7ab0d2' was
gathered on 2020/10/13.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Angelos Tsiaras                  2          2518           1170           36.84
gmorello                        67          4162           2162           63.16

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Angelos Tsiaras             890           35.3         10.1                2.58
gmorello                   2458           59.1          2.5               11.11
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2745 with the following error: 

 Could not find bibliography file: paper2.bib
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
👋 @gmorello -

* https://github.com/ucl-exoplanets/ExoTETHyS/blob/master/paper.md says the .bib file is paper2.bib, but that doesn't exist
* Your paper needs an explicit Statement of Need section
* We are having an internal editor discussion about the scope of the changes, to make sure they are sufficient for us to review a new version of this paper/software - because of this, I'm going to mark this as paused for now

**Comment by gmorello** [comment]
Dear Daniel S. Katz,

Thanks for the update.
I corrected the bibliography issue and added a Statement of Need.

Note that the new version is fully developed in the secondary branch v2-beta, and not in the master branch.
I wanted to pull the new version after its revision, but I was forced to move the paper.md in the master branch in order to submit to JOSS (and now I will have to fix the pull request).

Best,
Giuseppe
________________________________

**Comment by danielskatz** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #2745 with the following error: 

 pandoc-citeproc: reference magic2015 not found
[WARNING] Could not convert image '/tmp/tex2pdf.-674bcc2dae55b14f/628c60e7fd726b57bb67c4b13f831fa1e532bed8.svg': check that rsvg-convert is in path.
  rsvg-convert: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Error producing PDF.
! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-674bcc2dae55b1
4f/628c60e7fd726b57bb67c4b13f831fa1e532bed8.svg (no BoundingBox).

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.340 ...0e7fd726b57bb67c4b13f831fa1e532bed8.svg}}

Looks like we failed to compile the PDF

**Comment by danielskatz** [comment]
@gmorello - as you can see, there's still a problem here, perhaps related to the image in the file - can you take a look and see if can see a problem, then use the command I gave about to check if the PDF can be regenerated?

**Comment by gmorello** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02745/joss.02745/10.21105.joss.02745.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02745/joss.02745/10.21105.joss.02745.pdf) :page_facing_up: :point_left:

**Comment by gmorello** [comment]
@danielskatz Looks fine now, thanks.

**Comment by danielskatz** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201732147 is OK
- 10.1051/0004-6361/201219849 is OK
- 10.1051/0004-6361/201220942 is OK
- 10.1051/0004-6361/201833060 is OK
- 10.3847/1538-3881/abaabc is OK
- 10.1051/0004-6361/201423804 is OK
- 10.3847/1538-3881/abac09 is OK
- 10.3847/1538-3881/ab63dc is OK
- 10.1093/mnras/stz2958 is OK

MISSING DOIs

- 10.5194/epsc2020-67 may be a valid DOI for title: On The Compatibility of Ground-based and Space-based Data: WASP-96 b, An Example

INVALID DOIs

- None
```

**Comment by danielskatz** [comment]
@gmorello - please spell out all the journal names - we're not an astro-specific journal, so we don't use these abbreviations.  Also, please check to see if the above suggested DOI should be added to that bib entry.

**Comment by gmorello** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1051/0004-6361/201732147 is OK
- 10.1051/0004-6361/201219849 is OK
- 10.1051/0004-6361/201220942 is OK
- 10.1051/0004-6361/201833060 is OK
- 10.5194/epsc2020-67 is OK
- 10.3847/1538-3881/abaabc is OK
- 10.1051/0004-6361/201423804 is OK
- 10.3847/1538-3881/abac09 is OK
- 10.3847/1538-3881/ab63dc is OK
- 10.1093/mnras/stz2958 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by gmorello** [comment]
@danielskatz Done, thanks.

**Comment by arfon** [comment]
@gmorello - many thanks for your submission to JOSS. After consulting with the JOSS editorial board, we've determined that this second submission for ExoTETHyS is out of scope for JOSS.

My understanding is that the difference between this submission and the [first ExoTETHyS JOSS paper](https://joss.theoj.org/papers/10.21105/joss.01834) is the BOATS method, which is captured approximately in this diff: https://github.com/ucl-exoplanets/ExoTETHyS/compare/99266a44919a73167334e0e032a5ecbd4f9df75d...v2-beta

All JOSS submissions, be they the first, or subsequent efforts like this one, are required to meet the [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort). It is our determination that the work described in https://github.com/ucl-exoplanets/ExoTETHyS/compare/99266a44919a73167334e0e032a5ecbd4f9df75d...v2-beta does not meet this bar.

Please note this decision does not preclude a future follow-up ExoTETHyS JOSS submission. It's just that in this case, the _delta_ between the first and second papers is considered too minor.

**Comment by arfon** [comment]
@whedon reject

**Comment by whedon** [comment]
Paper rejected.

**Comment by gmorello** [comment]
Dear @arfon et al.,

Thank you for your time to consider this new submission.

Of course, I can only accept your decision although I am not convinced that the submission did not meet the [substantial scholarly effort criterion](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort):
- It took more than 3 months to complete the update, but it was mostly done on laptop so that the beta users could rely on a rather stable version instead of having continuous changes (this decreases the number of commits);
- The scope of the BOATS subpackage is significantly different on that of SAIL and TRIP, at least for the fact that BOATS models an effect induced by the planet, while SAIL and TRIP deals with stellar effects;
- One scientific paper has been already published that makes use of the BOATS algorithm (while in progress), and a second manuscript will be submitted today;
- It is unlikely that other algorithms similar to BOATS already exist;
- The BOATS subpackage alone contains more than 1000 lines of code (I counted 1815 lines, but this number includes the empty lines);
- The new interpolation method adopted by SAIL did notably speed-up the calculations, as we noted by running some examples (but did not spend time to measure this effect).

I recognize that it is still possible that it is out of scope for JOSS.
