### ISSUE TITLE
[REVIEW]: (py)oscode: fast solutions of oscillatory ODEs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#2830]
**Submitting author:** @fruzsinaagocs (<a href="http://orcid.org/0000-0002-1763-5884">Fruzsina Julia Agocs</a>)
**Repository:** <a href="https://github.com/fruzsinaagocs/oscode" target ="_blank">https://github.com/fruzsinaagocs/oscode</a>
**Version:** v1.0.3
**Editor:** @melissawm
**Reviewer:** @jakryd, @dlfivefifty
**Archive:** <a href="https://doi.org/10.5281/zenodo.4322958" target="_blank">10.5281/zenodo.4322958</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda/status.svg)](https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda"><img src="https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda/status.svg)](https://joss.theoj.org/papers/d4c9396ef9b2b595e2f3881a4f8a7cda)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fruzsinaagocs/oscode" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jakryd & @dlfivefifty, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @melissawm know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fruzsinaagocs/oscode">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fruzsinaagocs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fruzsinaagocs/oscode">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fruzsinaagocs) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jakryd, @dlfivefifty it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1103/PhysRevResearch.2.013030 is OK
- 10.1103/PhysRevD.101.043517 is OK
- 10.1103/PhysRevD.100.123517 is OK
- 10.1103/PhysRevD.102.023507 is OK
- 10.1137/0718030 is OK
- 10.1017/S0962492900002750 is OK
- 10.1016/j.acha.2016.05.002 is OK
- 10.1137/1.9781611975123 is OK
- 10.1007/bf03322583 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
👋🏼 @fruzsinaagocs, @jakryd, @dlfivefifty this is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#2830` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if any of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@melissawm) if you have any questions/concerns.

**Comment by melissawm** [comment]
Hello, @jakryd and @dlfivefifty, any updates on this review? Let me know if I can help you with anything.

**Comment by dlfivefifty** [comment]
I finished the review, everything looks fine. @fruzsinaagocs it's outside the scope of this review, but it would be interesting to compare performance with ApproxFun.jl, which also efficiently solves ODEs. E.g. look at the Airy example in the README:

https://github.com/JuliaApproximation/ApproxFun.jl

ApproxFun.jl doesn't do anything special for highly oscillatory problems, but, it is `O(n)` complexity for `n` degrees of freedom, and is pretty fast (around a second for a million unknowns). 

More interesting would be to do something special a la ultraspherical spectral method for the oscillatory case.  I did something for ODEs ages ago:

https://link.springer.com/chapter/10.1007%2F978-3-642-15337-2_24

Work by Keller gives some ideas for combining with the ultraspherical spectral method used in ApproxFun.jl. If this is of interest please let me know.

**Comment by melissawm** [comment]
Thank you, @dlfivefifty !

**Comment by melissawm** [comment]
@whedon re-invite @jakryd as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@jakryd please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by jakryd** [comment]
Thanks for re-inviting me. I finished the review, and I think that the package meets the JOSS requirements and format.

Congratulations @fruzsinaagocs!

**Comment by melissawm** [comment]
Thank you both @jakryd and @dlfivefifty for the review and congratulations @fruzsinaagocs! I'll generate a new proof and ask that you check that all references, author list, title, are as they should be so that we can proceed with acceptance.

**Comment by melissawm** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by fruzsinaagocs** [comment]
Thank you @melissawm, I fixed a capitalisation error in a reference and tweaked a sentence (really minor change to clarify that I'm referring to the expansion of the universe). With these changes, the paper's good to go!

**Comment by fruzsinaagocs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
Hello, @fruzsinaagocs ! A few small issues remain: 

- in [Deaño, Huybrechs, Iserles (2017)] the publisher is `Society for Industrial; Applied Mathematics` (there is an error rendering the `&` character, I believe)
- There is a citation by [Hu Li, B et al] that doesn't seem to correspond to the actual article. I think this is the right one (and also includes a DOI that is missing from the reference list): https://www.emerald.com/insight/content/doi/10.1108/03321640910999897/full/html Please confirm if this is the case.
- Some of the references contain full journal names (e.g. SIAM Journal on Numerical Analysis) and some contain abbreviated versions of the journal name (e.g. Phys. Rev. D). It would be better to have the full name for all journals as the practice of abbreviations varies between disciplines and some readers may not be familiar with that.
- A citation to [SciPy](https://scipy.org/citing.html) is missing in the summary.

Let me know when these are sorted so we can do a final check. Thanks!

**Comment by fruzsinaagocs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by fruzsinaagocs** [comment]
Thanks! I think this is all done now.

> * in [Deaño, Huybrechs, Iserles (2017)] the publisher is `Society for Industrial; Applied Mathematics` (there is an error rendering the `&` character, I believe)

Interestingly, bibTeX didn't like the word 'and' here. 

> * There is a citation by [Hu Li, B et al] that doesn't seem to correspond to the actual article. I think this is the right one (and also includes a DOI that is missing from the reference list): https://www.emerald.com/insight/content/doi/10.1108/03321640910999897/full/html Please confirm if this is the case.

Well spotted! I corrected this now, and it should have a doi.

> * Some of the references contain full journal names (e.g. SIAM Journal on Numerical Analysis) and some contain abbreviated versions of the journal name (e.g. Phys. Rev. D). It would be better to have the full name for all journals as the practice of abbreviations varies between disciplines and some readers may not be familiar with that.

All corrected to full journal names.

> * A citation to [SciPy](https://scipy.org/citing.html) is missing in the summary.

Added.

**Comment by fruzsinaagocs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
Hi @fruzsinaagocs one last thing, I think according to the DOI link the citation for [Condon et. al. 2009] should be

Condon, M., Deaño, A., Iserles, A., Maczyński, K. and Xu, T. (2009), "On numerical methods for highly oscillatory problems in circuit simulation", COMPEL - The international journal for computation and mathematics in electrical and electronic engineering, Vol. 28 No. 6, pp. 

(note the full journal name)

As far as I can tell this is the last step! Thanks again.

**Comment by fruzsinaagocs** [comment]
@melissawm Fixed it 😇

**Comment by fruzsinaagocs** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by melissawm** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1103/PhysRevResearch.2.013030 is OK
- 10.1103/PhysRevD.101.043517 is OK
- 10.1103/PhysRevD.100.123517 is OK
- 10.1103/PhysRevD.102.023507 is OK
- 10.1137/0718030 is OK
- 10.1017/S0962492900002750 is OK
- 10.1016/j.acha.2016.05.002 is OK
- 10.1108/03321640910999897 is OK
- 10.1137/1.9781611975123 is OK
- 10.1007/bf03322583 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by melissawm** [comment]
@fruzsinaagocs we are good to go! Can you please make a tagged release and archive (e.g. Zenodo), and report the DOI here?

**Comment by fruzsinaagocs** [comment]
Here's the Zenodo doi: 10.5281/zenodo.4322958

**Comment by melissawm** [comment]
Ok! It seems like the metadata for the Zenodo archive needs to be fixed. The title of the archive should match the title of the paper, and the author list should be the same, as well.

**Comment by fruzsinaagocs** [comment]
@melissawm Ah ok, I've edited it now (the doi should be the same).

**Comment by melissawm** [comment]
@whedon set 10.5281/zenodo.4322958 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.4322958" target="_blank">10.5281/zenodo.4322958</a> is the archive.

**Comment by melissawm** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41592-019-0686-2 is OK
- 10.1103/PhysRevResearch.2.013030 is OK
- 10.1103/PhysRevD.101.043517 is OK
- 10.1103/PhysRevD.100.123517 is OK
- 10.1103/PhysRevD.102.023507 is OK
- 10.1137/0718030 is OK
- 10.1017/S0962492900002750 is OK
- 10.1016/j.acha.2016.05.002 is OK
- 10.1108/03321640910999897 is OK
- 10.1137/1.9781611975123 is OK
- 10.1007/bf03322583 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1987

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1987, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by melissawm** [comment]
@fruzsinaagocs please check the final proof to make sure we didn't miss anything before publishing :)

**Comment by fruzsinaagocs** [comment]
@melissawm It all looks good :)

**Comment by kthyng** [comment]
Hi @fruzsinaagocs! I'm taking over to finish publication your work. Can you verify the version of the software you want associated with it? I see the newest version on the repo is v1.0.3.

**Comment by fruzsinaagocs** [comment]
@kthyng Yes, the version number is v1.0.3!

**Comment by kthyng** [comment]
@fruzsinaagocs Ok great, I'll update that.

Regarding your paper, just a few notes:
* I fixed some inline references in a [PR](https://github.com/fruzsinaagocs/oscode/pull/6), so please merge if you agree with them
* I can't quite tell how to fix the last sentence before the acknowledgments. If the reference is to be inline (without parentheses) then take the square brackets off. If it is meant to be parenthetically referenced, then keep the square brackets. You can have multiple references in one set of brackets, separated by a semi-colon. [More info](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by kthyng** [comment]
@whedon set v1.0.3 as version

**Comment by whedon** [comment]
OK. v1.0.3 is the version.

**Comment by fruzsinaagocs** [comment]
Thanks @kthyng, I've merged your PR and corrected another inline citation + the last citation.

**Comment by kthyng** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.02830/joss.02830/10.21105.joss.02830.pdf) :page_facing_up: :point_left:

**Comment by kthyng** [comment]
@fruzsinaagocs ok looks good! We can wrap up now.

**Comment by kthyng** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1338881155144294400) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1988
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.02830](https://doi.org/10.21105/joss.02830)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment]
Congrats on your new publication @fruzsinaagocs! Many thanks to editor @melissawm and reviewers @jakryd and @dlfivefifty — this wouldn't work without your time and expertise!

(I will close this issue once the doi resolves)

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.02830/status.svg)](https://doi.org/10.21105/joss.02830)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.02830">
  <img src="https://joss.theoj.org/papers/10.21105/joss.02830/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.02830/status.svg
   :target: https://doi.org/10.21105/joss.02830
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.02830/status.svg)](https://doi.org/10.21105/joss.02830)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss
