### ISSUE TITLE
[REVIEW]: Unishox: A hybrid encoder for Short Unicode Strings

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3919]
**Submitting author:** @siara-cc (<a href="http://orcid.org/0000-0001-6642-447X">Arundale Ramanathan</a>)
**Repository:** <a href="https://github.com/siara-cc/Unishox2" target ="_blank">https://github.com/siara-cc/Unishox2</a>
**Version:** 1.0.2
**Editor:** @gkthiruvathukal
**Reviewer:** @gradvohl, @linuxscout
**Archive:** <a href="https://doi.org/10.5281/zenodo.5800408" target="_blank">10.5281/zenodo.5800408</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg)](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58"><img src="https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58/status.svg)](https://joss.theoj.org/papers/ad4a75d706143f288528e1ffdcb6be58)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/siara-cc/Unishox2" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@gradvohl & @linuxscout, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @gradvohl
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/siara-cc/Unishox2">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/siara-cc/Unishox2">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@siara-cc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @linuxscout
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/siara-cc/Unishox2">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/siara-cc/Unishox2">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@siara-cc) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gradvohl, @linuxscout it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1844

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (311.4 files/s, 111138.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                                3            215            292           2932
C++                              1             68             64            995
TeX                              3            231              4            917
C/C++ Header                     3             45             74            163
Markdown                         2             77              0            154
YAML                             1              4              0             91
CMake                            3             12              0             58
JSON                             1              0              0             16
make                             1              3              0             10
-------------------------------------------------------------------------------
SUM:                            18            655            434           5336
-------------------------------------------------------------------------------


Statistical information for the repository 'fd239fb495b08133dd65a298' was
gathered on 2021/11/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Arun                            44          5920           1522           61.79
Arundale Ramanathan              1             2           1036            8.62
James Z.M. Gao                  24          1248            953           18.27
Jonathan Greenblatt              3          1261             17           10.61
Luis Diaz                        1             4              2            0.05
Luis Díaz Más                    5            36             43            0.66

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Arun                       2938           49.6         10.4               10.96
James Z.M. Gao              638           51.1          0.7                1.88
Jonathan Greenblatt        1244           98.7          6.1                7.72
Luis Díaz Más                28           77.8          1.4                0.00
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/tit.2004.834752 is OK
- 10.1002/j.1538-7305.1948.tb01338.x is OK
- 10.1109/JRPROC.1952.273898 is OK
- 10.1109/TIT.1977.1055714 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: :point_left:

**Comment by gradvohl** [comment]
# Reviewer report for JOSS paper #3919
**Paper title**: Unishox: A hybrid encoder for Short Unicode Strings

## Review criteria
* A list of the authors of the software: :heavy_check_mark:
* Author affiliations: :heavy_check_mark: (The author identifies himself as an "*Independent Researcher*").
* A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience: :heavy_check_mark: (Please see the [**Suggestions in the *Summary***](#suggestions-in-the-summary) section in the [**Reviewer Comments**](#reviewer-comments) section)
* A clear statement of need that illustrates the purpose of the software: :heavy_check_mark:
* Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it: :heavy_check_mark:  (Please see the [**Some additional information in the paper**](#some-additional-information-in-the-paper) section in the [**Reviewer Comments**](#reviewer-comments) section).
* A list of key references including a link to the software archive:  :wave: (sort of -- Please see the [**References in the paper**](#references-in-the-paper) section in the [**Reviewer Comments**](#reviewer-comments) section)

## Review items
* Software license: :thumbsup: (good -- Apache-2.0 License) 
* Substantial scholarly effort: :thumbsup: (good -- Please see the [**Scholarly effort**](#scholarly-effort)  section in the [**Reviewer Comments**](#reviewer-comments) section) 
* Documentation: 
    * A statement of need: :thumbsup: (good) 
    * Installation instructions: :thumbsup: (good) 
    * Example usage: :thumbsup: (good) 
    * API documentation: :thumbsdown: (**bad** -- Please see the [**API Docs**](#api-docs)  section in the [**Reviewer Comments**](#reviewer-comments) section) 
    * Community guidelines:  :thumbsdown: (**bad** -- Please see the [**Community guidelines**](#community-guidelines)  section in the [**Reviewer Comments**](#reviewer-comments) section)
    * Functionality: :thumbsup: (good) 
    * Tests: :thumbsup: (good)

* Software paper
    * Authors: :heavy_check_mark:
    * A statement of need: :heavy_check_mark:
    * Quality of writing: :wave: (sort of -- A little improvement in writing would be good. Perhaps an English native speaker may give interesting suggestions).
    * References: :heavy_check_mark: (Please see the [**References in the paper**](#references-in-the-paper)  section in the [**Reviewer Comments**](#reviewer-comments) section)

## Test environment
The reviewer conducted the tests for this software using an AWS instance (t2.micro) with Amazon Linux 2. 

## Reviewer comments
The following comments refer to items I considered  that could be improved, although they currently met the requirements for JOSS submission.

### Suggestions in the *Summary*
In the *Summary* section of the paper, the author claims that the "hybrid encoding method for compressing Short Unicode Strings of arbitrary lengths including Latin/English text and printable special characters (...) has not been sufficiently addressed by lossless encoding methods so far." It would be nice if he included an updated reference to support this statement. After all, most of the citations in the paper are more than five years old.

### Some additional information in the paper
The ``README.md`` file in the repository contains information about other projects that use ``Unishox``. However, those mentions are not in the ``paper.md`` file. It would be good if the author incorporated those mentions also in the ``paper.md`` file. Perhaps, in a specific section.

### References in the Paper
Please, add the link for the work of Burrows & Wheeler (1994) https://www.hpl.hp.com/techreports/Compaq-DEC/SRC-RR-124.pdf.

### Scholarly effort
I consider that there is a substantial scholarly effort producing this code. However, it would be nice if the author publishes a paper discussing the features and advantages of the ``Unishox2`` compared with other algorithms. Also, a publication in a scientific journal or a conference would be interesting. However, if the paper is on a preprint server (such as the Computer Science section of [arXiv](https://arxiv.org)) it is a significant first step.

### API Docs
I did not find any documentation about the code regarding the API documentation, neither in the ``docs`` directory (it contains only a ``.tex`` file), nor in the source code. Therefore, I strongly recommend the documentation of the source code using a standard. 
My suggestion is to use the [Doxygen](https://www.doxygen.nl/index.html) software. It can generate the docs (in HTML or PDF) from the documented source files.

### Community guidelines
Looking for information about how to contribute to Unishox2 software, I did not find any guidelines. There is only the **Issues** section in the repository, where there is the author's email to report issues or seek support. My suggestion is to create a **Contributing** section (or a ``CONTRIBUTING.md`` file) with more specific instructions about how to contribute.

### Other Suggestions
When I compiled with an older GCC version (``4.8.5``), the compiler issued the following error: ``‘for’ loop initial declarations are only allowed in C99 mode``. To avoid such problems, please inform the parameter ``-std=c99`` to the ``gcc`` compiler in the ``Makefile``.

Please, consider including the ``CITATION.cff`` file with information about how to cite the ``Unishox`` software. In addition, information about software citation in GitHub is available at [GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

## Conclusion
Analyzing all the aspects mentioned earlier, I rank the paper as **major revisions** needed. Although most of those revisions are very easy to implement, I consider that a lack of documentation prevents acceptance of the paper at this time.

**Comment by siara-cc** [comment]
Hi @gradvohl  Thank you for the detailed review and the valuable suggestions.  I am working on them and will update the docs quickly.

@gkthiruvathukal  @linuxscout

**Comment by siara-cc** [comment]
@gradvohl I have addressed all the points raised during review and made commits to the repo.  Please review to see if the changes meet expected standards when it is convenient.  I have also added the pre-review latex pdf as suggested to ResearchGate [at this url](https://www.researchgate.net/publication/356411501_Unishox_-A_hybrid_encoder_for_Short_Unicode_Strings) since arXiv is off-limits for an independent researcher like me.

Thanks again for spending time on this and the significant observations.

@whedon generate pdf

**Comment by gradvohl** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: :point_left:

**Comment by gradvohl** [comment]
Hello @siara-cc 

Sorry, but not all points were appropriately addressed. In my opinion, there are some missed points as follows:
1. The link for Burrows & Wheeler (1994)'s work in the reference section is still missing.
2. There are no comments on the source code using a standard (e.g., Doxygen or other software).
3. The CONTRIBUTING.md file misses the "project team" email (actually your email) in the "**Enforcement**" section.
4. To maintain compatibility with the new ``Makefile``, adding the ``-std=c99`` flag in the **Compiling** section in the ``README.md`` file would be significant.

Regarding the pre-review file, I see no problems publishing it on ResearchGate.net (although I prefer [Figshare](https://figshare.com) for this task). However, I am not sure if you did it right. The file is published at ResearchGate, indeed. Nevertheless, the DOI points to your repository (with the source files) and not to the paper itself. Take a look at the instructions to generate a DOI for your paper [here](https://explore.researchgate.net/display/support/ResearchGate+DOIs).

I believe that is it for now.

Best regards.

**Comment by gkthiruvathukal** [comment]
@gradvohl  Thanks for your comments.  @siara-cc, can you please address these as soon as possible?

@siara-cc Can you also clarify your points about ArXiv? It should absolutely not be "off-limits". I checked the submission requirements again, and don't think you are in any way prevented from submitting. If you mean that you are not allowed to post, it is just a matter of having an endorser. @gradvohl's suggestion of figshare is also a great option. I personally find it a lot easier to use than ArXiv!

@linuxscout Can you let us know when you have a chance to review the submission and fill in the checklist?

**Comment by siara-cc** [comment]
Hi @gradvohl ,

Thank you so much for reviewing it again. I have addressed these issues and please see my replies:

> 1. The link for Burrows & Wheeler (1994)'s work in the reference section is still missing.

I realise now that the URL is missing and I have added it now.  If my understanding is incorrect, please let me know.

> 2. There are no comments on the source code using a standard (e.g., Doxygen or other software).

I have added Doxygen comments to `unishox2.c`, `unishox2.h` and `test_unishox2.c`, which are the source code files related to the present version of Unishox (byte code version 2).  However, I have generated Doxygen pages only for `unishox2.h`, which describes the API functions.

The generated Doxygen API documentation can be found at: https://siara-cc.github.io/Unishox2/unishox2_8h.html

I have also addressed points (3) and (4).

Further, I have added the paper to FigShare [here](https://figshare.com/articles/preprint/Unishox_A_hybrid_encoder_for_Short_Unicode_Strings/17056334) with a DOI as suggested.  I also removed the one having incorrect DOI from ResearchGate.

As far as I have checked, I have addressed all the points.  If I have missed something or in case of other suggestions, please let me know.  I really appreciate the detailed review and advice. It will go a long way towards improving my future submissions.

**Comment by siara-cc** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: :point_left:

**Comment by siara-cc** [comment]
@gkthiruvathukal  Yes, I actually meant I did not know anyone who could endorse my work since I am not affiliated to an institution.  So I could not succeed in publishing with arXiv in the past.  However, I have published to figshare now successfully. Thanks.

**Comment by gkthiruvathukal** [comment]
@siara-cc Figshare is fine, for now. If you continue to publish and want to use ArXiv, you can reach out for an endorsement. I've had people ask me in the past. Figshare will do for now!

**Comment by siara-cc** [comment]
Sure, thanks @gkthiruvathukal !!

**Comment by gradvohl** [comment]
Hello @siara-cc,

I apologize for being so critical, but I am still not satisfied with some information in your repository.

First, I understand that you prefer to document the functions in the `.h` file, and I see no problems in doing this. However, in the "**File List**" section on the generated documentation, there is no reference to the ``unishox2.c`` file. Therefore, since you are expecting to publish in an **Open Source** Journal, I think that the documentation should point to the file that actually implements the code. So, please, include a reference to the ``unishox2.c`` file in the "**File List**" on the Doxygen generated documentation.

Second, regarding the [file uploaded to the Figshare](https://figshare.com/articles/preprint/Unishox_A_hybrid_encoder_for_Short_Unicode_Strings/17056334), when we click on the link you informed, it takes us to the Figshare site. However, the site reports that "``Linked content is NOT stored on Figshare, and we can't guarantee its availability, quality, security or accept any liability.``" and points us back to the paper your GitHub repository. Unfortunately, that is not what a reader expects. 

Having a DOI implies that the file (your paper in this case) is available right when we click on the DOI. Therefore, please, make your file ready for download (or read) in Figshare with a single click. In addition, as a suggestion, inform the reader about the paper in your main ``README.md`` file, so [&epsilon;|s]he can understand the theory/logic implemented in the code.

Best.

**Comment by siara-cc** [comment]
Hi @gradvohl , Sure, I have added `unishox2.c` to Doxygen doc and uploaded the actual PDF to figshare with a link in README.md.  I have documented each function and variable in `unishox2.c` to make it easy to understand for viewers and future contributors.  Thank you for pointing this out.

**Comment by gradvohl** [comment]
Hello @siara-cc,
In my opinion, everything is ok now. Congrats. :clap:

**Comment by siara-cc** [comment]
Hi @gradvohl Thank you and appreciate your patience 👍

**Comment by siara-cc** [comment]
Hi @gradvohl it still shows 2 items pending for the first review. Anything I need to do to close them ?
@gkthiruvathukal

**Comment by gradvohl** [comment]
Hello @siara-cc,
Your software does not cover the two items (Automated Tests and Performance claims). That is the reason why I left both items checked off.

**Comment by siara-cc** [comment]
Hi @gradvohl I have unit tests that provide good coverage and presented performance numbers in the performance section comparing to other competitive technologies. Also another person has made comprehensive tests and performance comparison with reddit posts as mentioned in the credits section. Kindly see if this meets thess requirements.

**Comment by gkthiruvathukal** [comment]
@gradvohl is right. In some cases, the items are not required. Being a software engineer myself, I like to see automatic tests  or unit tests but there are some cases where requiring it doesn't make sense.  

I'm still hoping to hear some input from @linuxscout. Based on the detailed review of @gradvohl and subsequent efforts by @siara-cc to resolve the issues, I feel like we are moving toward an acceptable submission. 

Given that the US holiday of Thanksgiving is just around the corner, I'm going to suggest that we wait for @linuxscout's review. We're in pretty good time on this submission so I'd like to allow for plenty of time for this review to be submitted before proceeding with the final decision, but things are looking encouraging!

**Comment by siara-cc** [comment]
Thanks @gkthiruvathukal but I have both unit tests and performance tests in place. Please see my reply here: https://github.com/openjournals/joss-reviews/issues/3919#issuecomment-976005023

**Comment by gkthiruvathukal** [comment]
@gradvohl  Can you please check? Or clarify what you mean by *does not cover*?  It would be great if you check both of these based on @siara-cc's follow up.

**Comment by gradvohl** [comment]
Hello @gkthiruvathukal and @siara-cc, 
As far as I know, the performance tests deal with memory and CPU usage metrics. Unfortunately, I did not find any information about those metrics in the repository. The fact that Unishox2 reaches better compression rates when compared to other software is essential, indeed. However, that fact is tied to the software's core and novelty, not its performance.

Considering the tests, although someone else did the tests, the results are not published on Unishox2 repository. Instead, it points to another repository.

I do not see any problems checking both items just to end the discussion. But I am not entirely convinced that those criteria are met.

**Comment by gkthiruvathukal** [comment]
@gradvohl Thanks for your clarification. It seems like there is nothing preventing acceptance here, but if any of these issues are blockers, please feel free to speak up. The JOSS approach is to make sure a submission results in as few open issues as possible, with the hope that the software delights users when they try to use it.

Regarding *unit tests*, my view is that if someone else did the tests--and they pass--mission accomplished!  Having said this, it would be nice if this repository shows that the tests are passing on each commit, but we don't require continuous integration (yet).

Please make sure you only check the items if you are comfortable. I can still accept, even if not all checkboxes are checked. However, I do need to give our other reviewer a chance to contribute his input before I can accept.

This constructive feedback and follow-up by the author is what JOSS is all about!!

**Comment by siara-cc** [comment]
Hi @gradvohl , Thank you for the clarification.  So far Unishox outperforms all other technologies on compression ratio and memory usage but not speed due to complexity of logic.  I have mentioned this in the documentation and have not been able to find a better way to present it so far.

I do have Unit tests and CI pipeline in the repo that does rigorous testing with API calls and files for several languages.

I respect your assessment about these and if these are not checked based on present status I am ok with it or if you require a specific metric to pass, I will include it.  Thank you for the comprehensive review.

@gkthiruvathukal

**Comment by siara-cc** [comment]
Hi @gradvohl  I apologise I probably was too eager in pointing out what was available and documented for unit tests and performance measurements.  Surely I was not pushing for undue credit.  I request you to kindly reassess and update the checklist reflecting the shortcomings or if you can let me know what I can do to improve it, I can at least try to earn the valuation given.

**Comment by gradvohl** [comment]
Dear @siara-cc ,
Please consider the comment from November/22nd (``In my opinion, everything is ok now. Congrats.`` :clap:) as my last one on this issue. BTW, all items in my Review Checklist are already checked. 
Best regards.

**Comment by linuxscout** [comment]
ٍSalam,
Add me to this issue to be able to check the checklist.
Thanks

**Comment by siara-cc** [comment]
@gradvohl Thank you for the prompt response and support.
@linuxscout Thank you for accepting to review my submission.  I am not sure the reviews are sequential and assigned automatically or assigned manually. So I defer to @gkthiruvathukal to advise on this.

**Comment by linuxscout** [comment]
I still not able to edit  (check) my reviewer checklist

**Comment by linuxscout** [comment]
Some review features need explanaition:
Documentation

- [ ] Installation instructions: need to be explained, but in this case, the author provided the C code, and many binding libraries for other languages. I thinks it's sufficient 

- [x] Example usage:  the C code is sufficient.

- [] Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified? Not given

**Comment by danielskatz** [comment]
@whedon re-invite @linuxscout as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@linuxscout please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment]
@linuxscout - if that doesn't work, let me know (there's a bug that might occur, but we can fix it by inviting you one more time)

**Comment by danielskatz** [comment]
@whedon re-invite @linuxscout as reviewer

**Comment by whedon** [comment]
OK, the reviewer has been re-invited.

@linuxscout please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by linuxscout** [comment]
Ok, It works,
I check all points.
There is one issue to handle, Automated tests.
I wait for author response.
Thanks

**Comment by gkthiruvathukal** [comment]
@linuxscout It looks like you are all set with the checklist now. Thanks for helping us to complete this review. upon hearing from @siara-cc, we should be able to proceed shortly toward acceptance.

**Comment by siara-cc** [comment]
Hi @linuxscout Thank you for pointing out this.  It was probably not clearly mentioned in README.md, but I have made a separate section now:

[Automated tests](https://github.com/siara-cc/Unishox2#unit-tests-automated)

Unit tests are implemented in `run_unit_tests()` function of `test_unishox2.c`, which tests all the features of Unishox2, including edge cases, using 159 strings covering several languages, emojis and binary data.

Further, the CI pipeline at `.github/workflows/c-cpp.yml` automates these tests for all presets and also tests file compression for the different types of files in `sample_texts` folder. This happens whenever a commit is made to the repository.

I apologise for the delay in response.

**Comment by linuxscout** [comment]
Thanks,
I finished the review.

**Comment by siara-cc** [comment]
Hi @linuxscout Thanks a lot !!

**Comment by gkthiruvathukal** [comment]
@linuxscout and @gradvohl: Thanks for your diligent efforts on these reviews.
@siara-cc Thanks for your responsiveness to the feedback!

For the reviewers, can you please react (simple thumbs up will do) to indicate whether you're ready to recommend this submission for acceptance?

**Comment by gradvohl** [comment]
👍🏼

**Comment by gkthiruvathukal** [comment]
Great, I will follow up with the next steps later this afternoon, after my Operating Systems lecture!

**Comment by siara-cc** [comment]
> For the reviewers, can you please react (simple thumbs up will do) to indicate whether you're ready to recommend this submission for acceptance?

Hi @linuxscout I think we are awaiting your response.

**Comment by gkthiruvathukal** [comment]
Yes, @siara-cc. I think @linuxscout is ready to move to accept but I will wait a bit just to be sure. I'm inclined to move to acceptance pretty soon though, since all issues seem to be addressed.

**Comment by linuxscout** [comment]
I recommend to accept this paper.

**Comment by gkthiruvathukal** [comment]
@siara-cc Please do the following:

- [ ] Make a tagged release of your software, and list the version tag of the archived version here. 
- [ ] Archive the reviewed software in Zenodo 
- [ ] Check the Zenodo deposit has the correct metadata, this includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it); you may also add the authors' ORCID.
- [ ] List the Zenodo DOI of the archived version here.

I will be taking a break until the 2nd of January but will process the final acceptance once you've completed all of the above. Cheers!

**Comment by siara-cc** [comment]
@gkthiruvathukal Thanks and I have done all of the above.  The tagged release version is `1.0.2` and Zenodo DOI is `10.5281/zenodo.5800408`.
Wish you merry Christmas and Happy New Year 2022.

**Comment by gkthiruvathukal** [comment]
Thank you, @siara-cc, especially for waiting for me. I became department chair at my university at the new year, so I am just getting back to *normal*.

**Comment by gkthiruvathukal** [comment]
@whedon set 10.5281/zenodo.5800408 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5800408" target="_blank">10.5281/zenodo.5800408</a> is the archive.

**Comment by gkthiruvathukal** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by gkthiruvathukal** [comment]
@whedon set 1.0.2 as version

**Comment by whedon** [comment]
OK. 1.0.2 is the version.

**Comment by gkthiruvathukal** [comment]
@whedon accept

**Comment by whedon** [comment]
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by gkthiruvathukal** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1109/tit.2004.834752 is OK
- 10.1002/j.1538-7305.1948.tb01338.x is OK
- 10.1109/JRPROC.1952.273898 is OK
- 10.1109/TIT.1977.1055714 is OK
- 10.4236/ijcns.2013.612053 is OK
- 10.1109/SAMI48414.2020.9108719 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2890

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2890, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by siara-cc** [comment]
> Thank you, @siara-cc, especially for waiting for me. I became department chair at my university at the new year, so I am just getting back to _normal_.

Thank you for taking this further and great news @gkthiruvathukal . Wish you more such accolades in future!!

**Comment by gkthiruvathukal** [comment]
Thank you, too, @siara-cc!

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03919/joss.03919/10.21105.joss.03919.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1483546415481733125) 👈 🐦🐦🐦

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2894
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03919](https://doi.org/10.21105/joss.03919)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment]
Congratulations @siara-cc on your article's publication in JOSS!

Many thanks to @gradvohl and @linuxscout for reviewing this submission, and @gkthiruvathukal for editing.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03919/status.svg)](https://doi.org/10.21105/joss.03919)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03919">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03919/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03919/status.svg
   :target: https://doi.org/10.21105/joss.03919
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03919/status.svg)](https://doi.org/10.21105/joss.03919)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by siara-cc** [comment]
Hi @kyleniemeyer Thats great news!! Thanks a lot for publishing Unishox with JOSS.
Thank you @gradvohl  and @linuxscout for patiently reviewing my submission.
Thank you @gkthiruvathukal for your guidance all the way.
