### ISSUE TITLE
[REVIEW]: Python Active-subspaces Utility Library

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#79]
**Submitting author:** @paulcon (<a href="http://orcid.org/0000-0003-3726-6307">Paul Constantine</a>)
**Repository:** <a href="https://github.com/paulcon/active_subspaces" target ="_blank">https://github.com/paulcon/active_subspaces</a>
**Version:** v 0.1
**Editor:** @kyleniemeyer
**Reviewer:** @mtezzele
**Archive:** <a href="http://doi.org/10.5281/zenodo.158941" target="_blank">10.5281/zenodo.158941</a>

## Status

[![status](http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a/status.svg)](http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a"><img src="http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a/status.svg)](http://joss.theoj.org/papers/a598bac0d7456ff4f94967c25ada0c0a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/paulcon/active_subspaces" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/paulcon/active_subspaces">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v 0.1)?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00079.pdf](https://github.com/openjournals/joss-reviews/files/487592/10.21105.joss.00079.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by kyleniemeyer** [comment]
Hi @mtezzele, the actual review will be performed in here, just FYI.

**Comment by nicoguaro** [comment]
:hand: I can review this

**Comment by kyleniemeyer** [comment]
@nicoguaro thanks! Both you and @mtezzele will be reviewing; it looks like we have a @whedon bug that only lets one person be the "official" reviewer at a time. Don't worry about that for now, we'll get it fixed.

**Comment by nicoguaro** [comment]
I installed the software in Windows 7 and ran the tests, that were successful.

I was trying to run the Jupyter notebook in the folder ``tutorials``, but it returns the following error in cell number 4.

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-4-1bdb1654efc5> in <module>()
          1 #This plots the eigenvalues (ss.eigenvalues) with bootstrap ranges (ss.e_br)
    ----> 2 ac.utils.plotters.eigenvalues(ss.eigenvalues, ss.e_br)
          3 
          4 #This plots subspace errors with bootstrap ranges (all contained in ss.sub_br)
          5 ac.utils.plotters.subspace_errors(ss.sub_br)

    AttributeError: Subspaces instance has no attribute 'eigenvalues'

**Comment by mtezzele** [comment]
Minor issue regarding the version: the release is 0.1 and the installed (now) is 0.1.1.

**Comment by paulcon** [comment]
Thanks for the help, reviewers! A few revisions:

(1) I have fixed the missing attribute errors in the notebooks. That was a consequence of a previous refactoring.
(2) I have corrected the version in setup.py to be consistent with the version release.
(3) I modified the code in utils/reponse_surfaces.py in such a way to remove the divide-by-zero RuntimeWarning.

Comments for @nicoguaro:
We have not developed/tested with Windows 10 / Anaconda, and we do not have easy access to such a system. All your failed tests fail on the same function. As best I can tell, this is not an issue with our code. I can find no bug, and tests pass on our systems. I'm not sure what to do with that one. Please advise.

Comments for @mtezzele:
(1) I have no specific guidelines for contributing. Anything that I would write would look like a github tutorial for forking, making a change, and submitting a pull request. I've also never written such a section, and I don't have any examples. If you have an example of such a section that I could mimic, please let me know.
(2) Regarding the documentation, we had mixed results using sphinx to build docs locally on different systems. It worked on some but not others. Therefore, we went with ReadTheDocs. It is set up to update automatically via a github webhook. So everyone should have access to the latest docs---based on the docstrings comments---through ReadTheDocs. To me, this is sufficient given the mixed success we had building sphinx locally. 

Thanks!

**Comment by mtezzele** [comment]
@paulcon I emailed to you an example of guidelines.

Some functions are not documented. See the last ones in the domains.py file for example.

After fixing these minor issues, to me the software is well written. Tests cover 90% of the code, documentation is clear and the examples provided explain the usage of the software well. 

I suggest to accept this work on JOSS.

**Comment by arfon** [comment]
@mtezzele thanks for the review here :zap: @nicoguaro - do you agree?

@paulcon if you can make these final changes (and pending @nicoguaro's approval) we can move forward with accepting this. Please note, once all changes have been made we need you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive.

**Comment by paulcon** [comment]
I have made the following changes:

(1) Updated community guidelines following a helpful example from @mtezzele 
(2) Expanded documentation for functions in domains.py, subpsaces.py, and utils/misc.py following the suggestions from @mtezzele. These are now updated in the latest build on ReadTheDocs.

If there anything else, please let me know. Thanks!

**Comment by kyleniemeyer** [comment]
Thanks @paulcon!

@mtezzele and @nicoguaro are your concerns/questions all satisfied? I see that a few checkboxes at the top of the issue are still empty—have those issues been resolved?

**Comment by mtezzele** [comment]
@kyleniemeyer all my concerns are satisfied.

**Comment by nicoguaro** [comment]
@kyleniemeyer, I have some comments

- It works fine in Linux Mint 18 (64 bits).
- I installed Gurobi (in Linux), but I can't tell if it is being used or not. When I ran the test, the elapsed time was about the same.
- The software works under Windows, if Python 32 bits is used.

Regarding the documentation that it should include more than just the docstrings from the code. Some points that I consider pertinent are below. Some examples (http://barbagroup.github.io/pygbe/docs/, http://cvxopt.org/documentation/index.html)

- Description of the software.
- Installation.
- How to use the software, examples. There is no need to repeat the notebooks, but maybe one or two examples. Considering that some of the examples are more expensive to run than others (like Ebola). Maybe a toy example (like this video: https://youtu.be/mJvKzjT6lmY) would be good.
- Link to the repository.
- FAQ, like in the website: http://activesubspaces.org/faq/

**Comment by paulcon** [comment]
Thanks, @nicoguaro. These are excellent suggestions for the documentation. I can have them done by next week.

**Comment by kyleniemeyer** [comment]
Great @paulcon! Please just update here when you're done, and we can wrap this up.

**Comment by paulcon** [comment]
I have updated the documentation following @nicoguaro's helpful suggestions. The only one I did not include was the FAQ. Instead, I pointed interested readers to the Active Subspaces website and the associated SIAM book.

Please let me know if you need anything else. Thanks!

**Comment by paulcon** [comment]
Oops... documentation example has a bug. One second...

**Comment by paulcon** [comment]
Okay, good to go.

**Comment by kyleniemeyer** [comment]
Thanks @paulcon! @nicoguaro it looks to me that your remaining issues have been satisfied, can you confirm?

If so, @paulcon the last step is for you to archive the latest version with Zenodo or figshare (e.g.), then let us know the resuting DOI here. (I'd also encourage you to add a badge to the README with the DOI.)

**Comment by nicoguaro** [comment]
@kyleniemeyer, @paulcon, it is good to go.

As a comment to @kyleniemeyer, can the generated PDF include the affiliation of authors 1-4 just once and use the superindex 1 to all of them?

**Comment by paulcon** [comment]
Here's the DOI:
http://doi.org/10.5281/zenodo.158941

What is the proper way to cite this, e.g., in BibTex?

**Comment by arfon** [comment]
> As a comment to @kyleniemeyer, can the generated PDF include the affiliation of authors 1-4 just once and use the superindex 1 to all of them?

@nicoguaro - can you reformat the paper metadata to look like this?  https://raw.githubusercontent.com/msmbuilder/osprey/master/paper/paper.md

**Comment by kyleniemeyer** [comment]
@arfon that should be directed at @paulcon 😄 

@paulcon That is a great question—I would normally do "Author, Title + version #, year, Zenodo, DOI". Now that you have the JOSS paper though, you can cite that instead (or in addition to).

**Comment by arfon** [comment]
> @arfon that should be directed at @paulcon 😄

Opps, sorry. @paulcon - can you reformat the paper metadata to look like this? https://raw.githubusercontent.com/msmbuilder/osprey/master/paper/paper.md

**Comment by paulcon** [comment]
Done. Thanks!

**Comment by arfon** [comment]
> Done. Thanks!

Great. If this paper looks good then I think we're good to accept? [10.21105.joss.00079.pdf](https://github.com/openjournals/joss-reviews/files/501490/10.21105.joss.00079.pdf)

**Comment by paulcon** [comment]
Looks good to me!

**Comment by nicoguaro** [comment]
Looks good!

**Comment by arfon** [comment]
@nicoguaro @mtezzele - many thanks for your reviews here.

@paulcon your paper is now accepted into JOSS. Your DOI is http://dx.doi.org/10.21105/joss.00079 🎉 🚀 💥
